### ISSUE TITLE
What's the license for this project?

### ISSUE THREAD

**Issue by jamietanna** [crazydisi/docker-teamspeak3#2]
This is the best Docker image I've found for Teamspeak3, due to being able to persistently store data, but as this doesn't have a license, I'm a bit apprehensive about using it (and indeed, making any changes). Could you please share thoughts on licensing?

**Comment by dphilpot** [comment]
Hi @jamietanna,

first of all sorry for the late answer, i'm quite bussy at the moment. 

For your Question: You can fork/use this Repository for free and make any changes you love to. If you think the change should make it back in this repository i would love to see a pull request, but its not mandatory.

I'll will make a better License description in the future. Thank you for the feedback!

Cheers,

Dennis

**Comment by jamietanna** [comment]
Thanks Dennis! Appreciate you getting back to me about this.

That's great to hear. Are you thinking that it'll be more something like a Permissive license (i.e. MIT) where changes _aren't_ required to be contributed back, or Copyleft (i.e. GPL), which does enforce this? I'd be pro Copyleft, and would be happy contributing back to you, but of course it's all up to you, as it is your work, after all!

**Comment by dphilpot** [comment]
Hi @jamietanna,

thanks for your feedback, thats exactly what i was thinking of too. I give it a few more thoughts and will update the License shortly.

Thanks for the feedback.

**Comment by jamietanna** [comment]
Hey @dphilpot any update on this?

**Comment by dphilpot** [comment]
Hi @jamietanna,

i finaly came to this small change. I Updated the License and added the current Teamspeak Server Version to the docker file.

Sorry for keept you waiting.

**Comment by dphilpot** [comment]
Took me quite some time from tablet to figure out why it wasn't building with the new version. The changed the name and the format of compression ....

**Comment by jamietanna** [comment]
No of course not - it's great you've added a license, as it now means I can contribute to help out :) Thanks again!

That's annoying, though - but glad you managed to get there.
